// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpdlZQ0r8DgGQBVgDNSf24z_gMK9us-40',
    appId: '1:243789631194:web:7c0562b5f28ebc69849fe3',
    messagingSenderId: '243789631194',
    projectId: 'messages-app-91991',
    authDomain: 'messages-app-91991.firebaseapp.com',
    storageBucket: 'messages-app-91991.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYQ20tuldsx0Ri-JKzTiy9WhyUgXLjzCw',
    appId: '1:243789631194:android:bf57494e6ddc0e56849fe3',
    messagingSenderId: '243789631194',
    projectId: 'messages-app-91991',
    storageBucket: 'messages-app-91991.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNarZeAiRrXUXwvDMgdN5o03fuHMdPi1M',
    appId: '1:243789631194:ios:318cc223db7e265a849fe3',
    messagingSenderId: '243789631194',
    projectId: 'messages-app-91991',
    storageBucket: 'messages-app-91991.appspot.com',
    androidClientId: '243789631194-3feapstkogmdvhnf2l4pu1a6uk7rbeks.apps.googleusercontent.com',
    iosClientId: '243789631194-j3n53c4ld3307povtndn1u33cc3hjmd9.apps.googleusercontent.com',
    iosBundleId: 'com.example.letsChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNarZeAiRrXUXwvDMgdN5o03fuHMdPi1M',
    appId: '1:243789631194:ios:318cc223db7e265a849fe3',
    messagingSenderId: '243789631194',
    projectId: 'messages-app-91991',
    storageBucket: 'messages-app-91991.appspot.com',
    androidClientId: '243789631194-3feapstkogmdvhnf2l4pu1a6uk7rbeks.apps.googleusercontent.com',
    iosClientId: '243789631194-j3n53c4ld3307povtndn1u33cc3hjmd9.apps.googleusercontent.com',
    iosBundleId: 'com.example.letsChat',
  );
}
